# Generated by Django 5.2.8 on 2025-12-08 15:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Straße')),
                ('city', models.CharField(max_length=50, verbose_name='Stadt')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postleitzahl')),
                ('country', models.CharField(default='Germany', max_length=50, verbose_name='Land')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_customers', to='shop.address', verbose_name='Standard Rechnungsadresse'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_customers', to='shop.address', verbose_name='Standard Versandadresse'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='shop.address', verbose_name='Rechnungsadresse'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_orders', to='shop.address', verbose_name='Versandadresse'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Betrag')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Zahlungsdatum')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('credit_card', 'Kreditkarte'), ('invoice', 'Rechnung'), ('bank_transfer', 'Überweisung')], max_length=32, verbose_name='Zahlungsmethode')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('refunded', 'Erstattet')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='Transaktions-ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.order', verbose_name='Bestellung')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_date', models.DateTimeField(blank=True, null=True, verbose_name='Versanddatum')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Zustelldatum')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Versanddienstleister')),
                ('tracking_number', models.CharField(blank=True, max_length=200, verbose_name='Tracking-Nummer')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('preparing', 'Wird vorbereitet'), ('shipped', 'Versendet'), ('in_transit', 'Unterwegs'), ('delivered', 'Zugestellt'), ('returned', 'Zurückgesendet')], default='pending', max_length=20, verbose_name='Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shop.order', verbose_name='Bestellung')),
            ],
            options={
                'verbose_name': 'Versand',
                'verbose_name_plural': 'Versendungen',
                'ordering': ['-shipped_date'],
            },
        ),
    ]
